apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: task_service:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/dbname"
            - name: KAFKA_BROKER
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: fastapi-app
spec:
  selector:
    app: task-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP